
  export const countries = [
    { icon: 'рџ‡¦рџ‡«', name: 'Afghanistan', abbr: 'AF', code: '93' },
    { icon: 'рџ‡¦рџ‡Ѕ', name: 'Alland Islands', abbr: 'AX', code: '358' },
    { icon: 'рџ‡¦рџ‡±', name: 'Albania', abbr: 'AL', code: '355' },
    { icon: 'рџ‡©рџ‡ї', name: 'Algeria', abbr: 'DZ', code: '213' },
    { icon: 'рџ‡¦рџ‡ё', name: 'American Samoa', abbr: 'AS', code: '1-684' },
    { icon: 'рџ‡¦рџ‡©', name: 'Andorra', abbr: 'AD', code: '376' },
    { icon: 'рџ‡¦рџ‡ґ', name: 'Angola', abbr: 'AO', code: '244' },
    { icon: 'рџ‡¦рџ‡®', name: 'Anguilla', abbr: 'AI', code: '1-264' },
    { icon: 'рџ‡¦рџ‡¶', name: 'Antarctica', abbr: 'AQ', code: '672' },
    { icon: 'рџ‡¦рџ‡¬', name: 'Antigua and Barbuda', abbr: 'AG', code: '1-268' },
    { icon: 'рџ‡¦рџ‡·', name: 'Argentina', abbr: 'AR', code: '54' },
    { icon: 'рџ‡¦рџ‡І', name: 'Armenia', abbr: 'AM', code: '374' },
    { icon: 'рџ‡¦рџ‡ј', name: 'Aruba', abbr: 'AW', code: '297' },
    { icon: 'рџ‡¦рџ‡є', name: 'Australia', abbr: 'AU', code: '61', suggested: true },
    { icon: 'рџ‡¦рџ‡№', name: 'Austria', abbr: 'AT', code: '43' },
    { icon: 'рџ‡¦рџ‡ї', name: 'Azerbaijan', abbr: 'AZ', code: '994' },
    { icon: 'рџ‡§рџ‡ё', name: 'Bahamas', abbr: 'BS', code: '1-242' },
    { icon: 'рџ‡§рџ‡­', name: 'Bahrain', abbr: 'BH', code: '973' },
    { icon: 'рџ‡§рџ‡©', name: 'Bangladesh', abbr: 'BD', code: '880' },
    { icon: 'рџ‡§рџ‡§', name: 'Barbados', abbr: 'BB', code: '1-246' },
    { icon: 'рџ‡§рџ‡ѕ', name: 'Belarus', abbr: 'BY', code: '375' },
    { icon: 'рџ‡§рџ‡Є', name: 'Belgium', abbr: 'BE', code: '32' },
    { icon: 'рџ‡§рџ‡ї', name: 'Belize', abbr: 'BZ', code: '501' },
    { icon: 'рџ‡§рџ‡Ї', name: 'Benin', abbr: 'BJ', code: '229' },
    { icon: 'рџ‡§рџ‡І', name: 'Bermuda', abbr: 'BM', code: '1-441' },
    { icon: 'рџ‡§рџ‡№', name: 'Bhutan', abbr: 'BT', code: '975' },
    { icon: 'рџ‡§рџ‡ґ', name: 'Bolivia', abbr: 'BO', code: '591' },
    { icon: 'рџ‡§рџ‡¦', name: 'Bosnia and Herzegovina', abbr: 'BA', code: '387' },
    { icon: 'рџ‡§рџ‡ј', name: 'Botswana', abbr: 'BW', code: '267' },
    { icon: 'рџ‡§рџ‡·', name: 'Brazil', abbr: 'BR', code: '55' },
    {
      icon: 'рџ‡®рџ‡ґ',
      name: 'British Indian Ocean Territory',
      abbr: 'IO',
      code: '246',
    },
    { icon: 'рџ‡»рџ‡¬', name: 'British Virgin Islands', abbr: 'VG', code: '1-284' },
    { icon: 'рџ‡§рџ‡і', name: 'Brunei Darussalam', abbr: 'BN', code: '673' },
    { icon: 'рџ‡§рџ‡¬', name: 'Bulgaria', abbr: 'BG', code: '359' },
    { icon: 'рџ‡§рџ‡«', name: 'Burkina Faso', abbr: 'BF', code: '226' },
    { icon: 'рџ‡§рџ‡®', name: 'Burundi', abbr: 'BI', code: '257' },
    { icon: 'рџ‡°рџ‡­', name: 'Cambodia', abbr: 'KH', code: '855' },
    { icon: 'рџ‡Ёрџ‡І', name: 'Cameroon', abbr: 'CM', code: '237' },
    { icon: 'рџ‡Ёрџ‡¦', name: 'Canada', abbr: 'CA', code: '1', suggested: true },
    { icon: 'рџ‡Ёрџ‡»', name: 'Cape Verde', abbr: 'CV', code: '238' },
    { icon: 'рџ‡°рџ‡ѕ', name: 'Cayman Islands', abbr: 'KY', code: '1-345' },
    { icon: 'рџ‡Ёрџ‡«', name: 'Central African Republic', abbr: 'CF', code: '236' },
    { icon: 'рџ‡№рџ‡©', name: 'Chad', abbr: 'TD', code: '235' },
    { icon: 'рџ‡Ёрџ‡±', name: 'Chile', abbr: 'CL', code: '56' },
    { icon: 'рџ‡Ёрџ‡і', name: 'China', abbr: 'CN', code: '86' },
    { icon: 'рџ‡Ёрџ‡Ѕ', name: 'Christmas Island', abbr: 'CX', code: '61' },
    { icon: 'рџ‡Ёрџ‡ґ', name: 'Colombia', abbr: 'CO', code: '57' },
    { icon: 'рџ‡°рџ‡І', name: 'Comoros', abbr: 'KM', code: '269' },
    {
      icon: 'рџ‡Ёрџ‡©',
      name: 'Congo, Democratic Republic of the',
      abbr: 'CG',
      code: '243',
    },
    {
      icon: 'рџ‡Ёрџ‡¬',
      name: 'Congo, Republic of the',
      abbr: 'CD',
      code: '242',
    },
    { icon: 'рџ‡Ёрџ‡°', name: 'Cook Islands', abbr: 'CK', code: '682' },
    { icon: 'рџ‡Ёрџ‡·', name: 'Costa Rica', abbr: 'CR', code: '506' },
    { icon: 'рџ‡Ёрџ‡®', name: "Cote d'Ivoire", abbr: 'CI', code: '225' },
    { icon: 'рџ‡­рџ‡·', name: 'Croatia', abbr: 'HR', code: '385' },
    { icon: 'рџ‡Ёрџ‡є', name: 'Cuba', abbr: 'CU', code: '53' },
    { icon: 'рџ‡Ёрџ‡ј', name: 'Curacao', abbr: 'CW', code: '599' },
    { icon: 'рџ‡Ёрџ‡ѕ', name: 'Cyprus', abbr: 'CY', code: '357' },
    { icon: 'рџ‡Ёрџ‡ї', name: 'Czech Republic', abbr: 'CZ', code: '420' },
    { icon: 'рџ‡©рџ‡°', name: 'Denmark', abbr: 'DK', code: '45' },
    { icon: 'рџ‡©рџ‡Ї', name: 'Djibouti', abbr: 'DJ', code: '253' },
    { icon: 'рџ‡©рџ‡І', name: 'Dominica', abbr: 'DM', code: '1-767' },
    { icon: 'рџ‡©рџ‡ґ', name: 'Dominican Republic', abbr: 'DO', code: '1-809' },
    { icon: 'рџ‡Єрџ‡Ё', name: 'Ecuador', abbr: 'EC', code: '593' },
    { icon: 'рџ‡Єрџ‡¬', name: 'Egypt', abbr: 'EG', code: '20' },
    { icon: 'рџ‡ёрџ‡»', name: 'El Salvador', abbr: 'SV', code: '503' },
    { icon: 'рџ‡¬рџ‡¶', name: 'Equatorial Guinea', abbr: 'GQ', code: '240' },
    { icon: 'рџ‡Єрџ‡·', name: 'Eritrea', abbr: 'ER', code: '291' },
    { icon: 'рџ‡Єрџ‡Є', name: 'Estonia', abbr: 'EE', code: '372' },
    { icon: 'рџ‡Єрџ‡№', name: 'Ethiopia', abbr: 'ET', code: '251' },
    { icon: 'рџ‡«рџ‡°', name: 'Falkland Islands (Malvinas)', abbr: 'FK', code: '500' },
    { icon: 'рџ‡«рџ‡ґ', name: 'Faroe Islands', abbr: 'FO', code: '298' },
    { icon: 'рџ‡«рџ‡Ї', name: 'Fiji', abbr: 'FJ', code: '679' },
    { icon: 'рџ‡«рџ‡®', name: 'Finland', abbr: 'FI', code: '358' },
    { icon: 'рџ‡«рџ‡·', name: 'France', abbr: 'FR', code: '33', suggested: true },
    { icon: 'рџ‡¬рџ‡«', name: 'French Guiana', abbr: 'GF', code: '594' },
    { icon: 'рџ‡µрџ‡«', name: 'French Polynesia', abbr: 'PF', code: '689' },
    { icon: 'рџ‡№рџ‡«', name: 'French Southern Territories', abbr: 'TF', code: '262' },
    { icon: 'рџ‡¬рџ‡¦', name: 'Gabon', abbr: 'GA', code: '241' },
    { icon: 'рџ‡¬рџ‡І', name: 'Gambia', abbr: 'GM', code: '220' },
    { icon: 'рџ‡¬рџ‡Є', name: 'Georgia', abbr: 'GE', code: '995' },
    { icon: 'рџ‡©рџ‡Є', name: 'Germany', abbr: 'DE', code: '49', suggested: true },
    { icon: 'рџ‡¬рџ‡­', name: 'Ghana', abbr: 'GH', code: '233' },
    { icon: 'рџ‡¬рџ‡®', name: 'Gibraltar', abbr: 'GI', code: '350' },
    { icon: 'рџ‡¬рџ‡·', name: 'Greece', abbr: 'GR', code: '30' },
    { icon: 'рџ‡¬рџ‡±', name: 'Greenland', abbr: 'GL', code: '299' },
    { icon: 'рџ‡¬рџ‡©', name: 'Grenada', abbr: 'GD', code: '1-473' },
    { icon: 'рџ‡¬рџ‡µ', name: 'Guadeloupe', abbr: 'GP', code: '590' },
    { icon: 'рџ‡¬рџ‡є', name: 'Guam', abbr: 'GU', code: '1-671' },
    { icon: 'рџ‡¬рџ‡№', name: 'Guatemala', abbr: 'GT', code: '502' },
    { icon: 'рџ‡¬рџ‡ј', name: 'Guinea-Bissau', abbr: 'GW', code: '245' },
    { icon: 'рџ‡¬рџ‡і', name: 'Guinea', abbr: 'GN', code: '224' },
    { icon: 'рџ‡¬рџ‡ѕ', name: 'Guyana', abbr: 'GY', code: '592' },
    { icon: 'рџ‡­рџ‡№', name: 'Haiti', abbr: 'HT', code: '509' },
    {
      icon: 'рџ‡­рџ‡І',
      name: 'Heard Island and McDonald Islands',
      abbr: 'HM',
      code: '672',
    },
    {
      icon: 'рџ‡»рџ‡¦',
      name: 'Holy See (Vatican City State)',
      abbr: 'VA',
      code: '379',
    },
    { icon: 'рџ‡­рџ‡і', name: 'Honduras', abbr: 'HN', code: '504' },
    { icon: 'рџ‡­рџ‡°', name: 'Hong Kong', abbr: 'HK', code: '852' },
    { icon: 'рџ‡­рџ‡є', name: 'Hungary', abbr: 'HU', code: '36' },
    { icon: 'рџ‡®рџ‡ё', name: 'Iceland', abbr: 'IS', code: '354' },
    { icon: 'рџ‡®рџ‡і', name: 'India', abbr: 'IN', code: '91' },
    { icon: 'рџ‡®рџ‡©', name: 'Indonesia', abbr: 'ID', code: '62' },
    { icon: 'рџ‡®рџ‡·', name: 'Iran, Islamic Republic of', abbr: 'IR', code: '98' },
    { icon: 'рџ‡®рџ‡¶', name: 'Iraq', abbr: 'IQ', code: '964' },
    { icon: 'рџ‡®рџ‡Є', name: 'Ireland', abbr: 'IE', code: '353' },
    { icon: 'рџ‡®рџ‡±', name: 'Israel', abbr: 'IL', code: '972' },
    { icon: 'рџ‡®рџ‡№', name: 'Italy', abbr: 'IT', code: '39' },
    { icon: 'рџ‡Їрџ‡І', name: 'Jamaica', abbr: 'JM', code: '1-876' },
    { icon: 'рџ‡Їрџ‡µ', name: 'Japan', abbr: 'JP', code: '81', suggested: true },
    { icon: 'рџ‡Їрџ‡ґ', name: 'Jordan', abbr: 'JO', code: '962' },
    { icon: 'рџ‡°рџ‡ї', name: 'Kazakhstan', abbr: 'KZ', code: '7' },
    { icon: 'рџ‡°рџ‡Є', name: 'Kenya', abbr: 'KE', code: '254' },
    { icon: 'рџ‡°рџ‡®', name: 'Kiribati', abbr: 'KI', code: '686' },
    {
      icon: 'рџ‡°рџ‡µ',
      name: "Korea, Democratic People's Republic of",
      abbr: 'KP',
      code: '850',
    },
    { icon: 'рџ‡°рџ‡·', name: 'Korea, Republic of', abbr: 'KR', code: '82' },
    { icon: 'рџ‡Ѕрџ‡°', name: 'Kosovo', abbr: 'XK', code: '383' },
    { icon: 'рџ‡°рџ‡ј', name: 'Kuwait', abbr: 'KW', code: '965' },
    { icon: 'рџ‡°рџ‡¬', name: 'Kyrgyzstan', abbr: 'KG', code: '996' },
    {
      icon: 'рџ‡±рџ‡¦',
      name: "Lao People's Democratic Republic",
      abbr: 'LA',
      code: '856',
    },
    { icon: 'рџ‡±рџ‡»', name: 'Latvia', abbr: 'LV', code: '371' },
    { icon: 'рџ‡±рџ‡§', name: 'Lebanon', abbr: 'LB', code: '961' },
    { icon: 'рџ‡±рџ‡ё', name: 'Lesotho', abbr: 'LS', code: '266' },
    { icon: 'рџ‡±рџ‡·', name: 'Liberia', abbr: 'LR', code: '231' },
    { icon: 'рџ‡±рџ‡ѕ', name: 'Libya', abbr: 'LY', code: '218' },
    { icon: 'рџ‡±рџ‡®', name: 'Liechtenstein', abbr: 'LI', code: '423' },
    { icon: 'рџ‡±рџ‡№', name: 'Lithuania', abbr: 'LT', code: '370' },
    { icon: 'рџ‡±рџ‡є', name: 'Luxembourg', abbr: 'LU', code: '352' },
    { icon: 'рџ‡Ірџ‡ґ', name: 'Macao', abbr: 'MO', code: '853' },
    {
      icon: 'рџ‡Ірџ‡°',
      name: 'Macedonia, the Former Yugoslav Republic of',
      abbr: 'MK',
      code: '389',
    },
    { icon: 'рџ‡Ірџ‡¬', name: 'Madagascar', abbr: 'MG', code: '261' },
    { icon: 'рџ‡Ірџ‡ј', name: 'Malawi', abbr: 'MW', code: '265' },
    { icon: 'рџ‡Ірџ‡ѕ', name: 'Malaysia', abbr: 'MY', code: '60' },
    { icon: 'рџ‡Ірџ‡»', name: 'Maldives', abbr: 'MV', code: '960' },
    { icon: 'рџ‡Ірџ‡±', name: 'Mali', abbr: 'ML', code: '223' },
    { icon: 'рџ‡Ірџ‡№', name: 'Malta', abbr: 'MT', code: '356' },
    { icon: 'рџ‡Ірџ‡­', name: 'Marshall Islands', abbr: 'MH', code: '692' },
    { icon: 'рџ‡Ірџ‡¶', name: 'Martinique', abbr: 'MQ', code: '596' },
    { icon: 'рџ‡Ірџ‡·', name: 'Mauritania', abbr: 'MR', code: '222' },
    { icon: 'рџ‡Ірџ‡є', name: 'Mauritius', abbr: 'MU', code: '230' },
    { icon: 'рџ‡ѕрџ‡№', name: 'Mayotte', abbr: 'YT', code: '262' },
    { icon: 'рџ‡Ірџ‡Ѕ', name: 'Mexico', abbr: 'MX', code: '52' },
    {
      icon: 'рџ‡«рџ‡І',
      name: 'Micronesia, Federated States of',
      abbr: 'FM',
      code: '691',
    },
    { icon: 'рџ‡Ірџ‡©', name: 'Moldova, Republic of', abbr: 'MD', code: '373' },
    { icon: 'рџ‡Ірџ‡Ё', name: 'Monaco', abbr: 'MC', code: '377' },
    { icon: 'рџ‡Ірџ‡і', name: 'Mongolia', abbr: 'MN', code: '976' },
    { icon: 'рџ‡Ірџ‡Є', name: 'Montenegro', abbr: 'ME', code: '382' },
    { icon: 'рџ‡Ірџ‡ё', name: 'Montserrat', abbr: 'MS', code: '1-664' },
    { icon: 'рџ‡Ірџ‡¦', name: 'Morocco', abbr: 'MA', code: '212' },
    { icon: 'рџ‡Ірџ‡ї', name: 'Mozambique', abbr: 'MZ', code: '258' },
    { icon: 'рџ‡Ірџ‡І', name: 'Myanmar', abbr: 'MM', code: '95' },
    { icon: 'рџ‡ірџ‡¦', name: 'Namibia', abbr: 'NA', code: '264' },
    { icon: 'рџ‡ірџ‡·', name: 'Nauru', abbr: 'NR', code: '674' },
    { icon: 'рџ‡ірџ‡µ', name: 'Nepal', abbr: 'NP', code: '977' },
    { icon: 'рџ‡ірџ‡±', name: 'Netherlands', abbr: 'NL', code: '31' },
    { icon: 'рџ‡ірџ‡Ё', name: 'New Caledonia', abbr: 'NC', code: '687' },
    { icon: 'рџ‡ірџ‡ї', name: 'New Zealand', abbr: 'NZ', code: '64' },
    { icon: 'рџ‡ірџ‡®', name: 'Nicaragua', abbr: 'NI', code: '505' },
    { icon: 'рџ‡ірџ‡Є', name: 'Niger', abbr: 'NE', code: '227' },
    { icon: 'рџ‡ірџ‡¬', name: 'Nigeria', abbr: 'NG', code: '234' },
    { icon: 'рџ‡ірџ‡є', name: 'Niue', abbr: 'NU', code: '683' },
    { icon: 'рџ‡ірџ‡«', name: 'Norfolk Island', abbr: 'NF', code: '672' },
    { icon: 'рџ‡Ірџ‡µ', name: 'Northern Mariana Islands', abbr: 'MP', code: '1-670' },
    { icon: 'рџ‡ірџ‡ґ', name: 'Norway', abbr: 'NO', code: '47' },
    { icon: 'рџ‡ґрџ‡І', name: 'Oman', abbr: 'OM', code: '968' },
    { icon: 'рџ‡µрџ‡°', name: 'Pakistan', abbr: 'PK', code: '92' },
    { icon: 'рџ‡µрџ‡ј', name: 'Palau', abbr: 'PW', code: '680' },
    { icon: 'рџ‡µрџ‡ё', name: 'Palestine, State of', abbr: 'PS', code: '970' },
    { icon: 'рџ‡µрџ‡¦', name: 'Panama', abbr: 'PA', code: '507' },
    { icon: 'рџ‡µрџ‡¬', name: 'Papua New Guinea', abbr: 'PG', code: '675' },
    { icon: 'рџ‡µрџ‡ѕ', name: 'Paraguay', abbr: 'PY', code: '595' },
    { icon: 'рџ‡µрџ‡Є', name: 'Peru', abbr: 'PE', code: '51' },
    { icon: 'рџ‡µрџ‡­', name: 'Philippines', abbr: 'PH', code: '63' },
    { icon: 'рџ‡µрџ‡і', name: 'Pitcairn', abbr: 'PN', code: '870' },
    { icon: 'рџ‡µрџ‡±', name: 'Poland', abbr: 'PL', code: '48' },
    { icon: 'рџ‡µрџ‡№', name: 'Portugal', abbr: 'PT', code: '351' },
    { icon: 'рџ‡¶рџ‡¦', name: 'Qatar', abbr: 'QA', code: '974' },
    { icon: 'рџ‡·рџ‡Є', name: 'Reunion', abbr: 'RE', code: '262' },
    { icon: 'рџ‡·рџ‡ґ', name: 'Romania', abbr: 'RO', code: '40' },
    { icon: 'рџ‡·рџ‡є', name: 'Russian Federation', abbr: 'RU', code: '7' },
    { icon: 'рџ‡·рџ‡ј', name: 'Rwanda', abbr: 'RW', code: '250' },
    { icon: 'рџ‡ёрџ‡­', name: 'Saint Helena', abbr: 'SH', code: '290' },
    { icon: 'рџ‡°рџ‡і', name: 'Saint Kitts and Nevis', abbr: 'KN', code: '1-869' },
    { icon: 'рџ‡±рџ‡Ё', name: 'Saint Lucia', abbr: 'LC', code: '1-758' },
    { icon: 'рџ‡µрџ‡І', name: 'Saint Pierre and Miquelon', abbr: 'PM', code: '508' },
    {
      icon: 'рџ‡»рџ‡Ё',
      name: 'Saint Vincent and the Grenadines',
      abbr: 'VC',
      code: '1-784',
    },
    { icon: 'рџ‡јрџ‡ё', name: 'Samoa', abbr: 'WS', code: '685' },
    { icon: 'рџ‡ёрџ‡І', name: 'San Marino', abbr: 'SM', code: '378' },
    { icon: 'рџ‡ёрџ‡№', name: 'Sao Tome and Principe', abbr: 'ST', code: '239' },
    { icon: 'рџ‡ёрџ‡¦', name: 'Saudi Arabia', abbr: 'SA', code: '966' },
    { icon: 'рџ‡ёрџ‡і', name: 'Senegal', abbr: 'SN', code: '221' },
    { icon: 'рџ‡·рџ‡ё', name: 'Serbia', abbr: 'RS', code: '381' },
    { icon: 'рџ‡ёрџ‡Ё', name: 'Seychelles', abbr: 'SC', code: '248' },
    { icon: 'рџ‡ёрџ‡±', name: 'Sierra Leone', abbr: 'SL', code: '232' },
    { icon: 'рџ‡ёрџ‡¬', name: 'Singapore', abbr: 'SG', code: '65' },
    { icon: 'рџ‡ёрџ‡Ѕ', name: 'Sint Maarten (Dutch part)', abbr: 'SX', code: '1-721' },
    { icon: 'рџ‡ёрџ‡°', name: 'Slovakia', abbr: 'SK', code: '421' },
    { icon: 'рџ‡ёрџ‡®', name: 'Slovenia', abbr: 'SI', code: '386' },
    { icon: 'рџ‡ёрџ‡§', name: 'Solomon Islands', abbr: 'SB', code: '677' },
    { icon: 'рџ‡ёрџ‡ґ', name: 'Somalia', abbr: 'SO', code: '252' },
    { icon: 'рџ‡їрџ‡¦', name: 'South Africa', abbr: 'ZA', code: '27' },
    {
      icon: 'рџ‡¬рџ‡ё',
      name: 'South Georgia and the South Sandwich Islands',
      abbr: 'GS',
      code: '500',
    },
    { icon: 'рџ‡ёрџ‡ё', name: 'South Sudan', abbr: 'SS', code: '211' },
    { icon: 'рџ‡Єрџ‡ё', name: 'Spain', abbr: 'ES', code: '34' },
    { icon: 'рџ‡±рџ‡°', name: 'Sri Lanka', abbr: 'LK', code: '94' },
    { icon: 'рџ‡ёрџ‡©', name: 'Sudan', abbr: 'SD', code: '249' },
    { icon: 'рџ‡ёрџ‡·', name: 'Suriname', abbr: 'SR', code: '597' },
    { icon: 'рџ‡ёрџ‡ї', name: 'Swaziland', abbr: 'SZ', code: '268' },
    { icon: 'рџ‡ёрџ‡Є', name: 'Sweden', abbr: 'SE', code: '46' },
    { icon: 'рџ‡Ёрџ‡­', name: 'Switzerland', abbr: 'CH', code: '41' },
    { icon: 'рџ‡ёрџ‡ѕ', name: 'Syrian Arab Republic', abbr: 'SY', code: '963' },
    { icon: 'рџ‡№рџ‡ј', name: 'Taiwan, Province of China', abbr: 'TW', code: '886' },
    { icon: 'рџ‡№рџ‡Ї', name: 'Tajikistan', abbr: 'TJ', code: '992' },
    { icon: 'рџ‡№рџ‡­', name: 'Thailand', abbr: 'TH', code: '66' },
    { icon: 'рџ‡№рџ‡±', name: 'Timor-Leste', abbr: 'TL', code: '670' },
    { icon: 'рџ‡№рџ‡¬', name: 'Togo', abbr: 'TG', code: '228' },
    { icon: 'рџ‡№рџ‡°', name: 'Tokelau', abbr: 'TK', code: '690' },
    { icon: 'рџ‡№рџ‡ґ', name: 'Tonga', abbr: 'TO', code: '676' },
    { icon: 'рџ‡№рџ‡№', name: 'Trinidad and Tobago', abbr: 'TT', code: '1-868' },
    { icon: 'рџ‡№рџ‡і', name: 'Tunisia', abbr: 'TN', code: '216' },
    { icon: 'рџ‡№рџ‡·', name: 'Turkey', abbr: 'TR', code: '90' },
    { icon: 'рџ‡№рџ‡І', name: 'Turkmenistan', abbr: 'TM', code: '993' },
    { icon: 'рџ‡№рџ‡Ё', name: 'Turks and Caicos Islands', abbr: 'TC', code: '1-649' },
    { icon: 'рџ‡№рџ‡»', name: 'Tuvalu', abbr: 'TV', code: '688' },
    { icon: 'рџ‡єрџ‡¬', name: 'Uganda', abbr: 'UG', code: '256' },
    { icon: 'рџ‡єрџ‡¦', name: 'Ukraine', abbr: 'UA', code: '380' },
    { icon: 'рџ‡¦рџ‡Є', name: 'United Arab Emirates', abbr: 'AE', code: '971' },
    { icon: 'рџ‡¬рџ‡§', name: 'United Kingdom', abbr: 'GB', code: '44' },
    { icon: 'рџ‡№рџ‡ї', name: 'United Republic of Tanzania', abbr: 'TZ', code: '255' },
    { icon: 'рџ‡єрџ‡І', name: 'United States', abbr: 'US', code: '1-1', suggested: true },
    { icon: 'рџ‡єрџ‡ѕ', name: 'Uruguay', abbr: 'UY', code: '598' },
    { icon: 'рџ‡»рџ‡®', name: 'US Virgin Islands', abbr: 'VI', code: '1-340' },
    { icon: 'рџ‡єрџ‡ї', name: 'Uzbekistan', abbr: 'UZ', code: '998' },
    { icon: 'рџ‡»рџ‡є', name: 'Vanuatu', abbr: 'VU', code: '678' },
    { icon: 'рџ‡»рџ‡Є', name: 'Venezuela', abbr: 'VE', code: '58' },
    { icon: 'рџ‡»рџ‡і', name: 'Vietnam', abbr: 'VN', code: '84' },
    { icon: 'рџ‡јрџ‡«', name: 'Wallis and Futuna', abbr: 'WF', code: '681' },
    { icon: 'рџ‡ѕрџ‡Є', name: 'Yemen', abbr: 'YE', code: '967' },
    { icon: 'рџ‡їрџ‡І', name: 'Zambia', abbr: 'ZM', code: '260' },
    { icon: 'рџ‡їрџ‡ј', name: 'Zimbabwe', abbr: 'ZW', code: '263' },
  ];
  
  // separate countries into groups
  // export const countries: Array<{
  //   label: string,
  //   options: Array<Country>,
  // }> = [
  //   {
  //     label: 'Suggested',
  //     options: allCountries.filter(c => c.suggested),
  //   },
  //   {
  //     label: 'All Countries',
  //     options: allCountries.filter(c => !c.suggested),
  //   },
  // ];